# Generated by Django 5.0.6 on 2024-07-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_created_at_alter_record_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
